basic_app/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from register import views as views_2

app_name = 'basic_app'

urlpatterns = [
    path('', views.index , name='index'),
    path('login', views.user_login , name='login'),
    path('register', views.user_register , name='register'),
   
]

myproject_1/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls'))
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

JOB_CHOICES = (
    (1, "Designer"),
    (2, "Manager"),
    (3, "Accounting")
)
CONTACT_CHOICES = (
    (1, "+91"),
    (2, "+92"),
    (3, "+93"),
)

class UserInfoModel(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    
    fullname = models.CharField(max_length=264,unique=True)
    email = models.EmailField(max_length=255)
    contact_pref = models.IntegerField(choices=CONTACT_CHOICES, default=1)
    contact_suff =models.IntegerField()
    job= models.IntegerField(choices=JOB_CHOICES, default=1)
    pwd1 = models.CharField(max_length=20)
    pwd2 = models.CharField(max_length=20)

    def __str__(self):
        return user.fullname

register/models.py
from django.db import models

# Create your models here.

basic_app/forms.py
from django import forms
from basic_app.models import UserInfoModel
from django.contrib.auth.models import User

JOB_CHOICES = (
    (1, "Designer"),
    (2, "Manager"),
    (3, "Accounting")
)
CONTACT_CHOICES = (
    (1, "+91"),
    (2, "+92"),
    (3, "+93"),
)

class RegisterForm(forms.ModelForm):

    fullname = forms.CharField(max_length=264,widget=forms.TextInput(attrs={'class':'form-control'}))

    email = forms.EmailField(max_length=255,widget=forms.EmailInput(attrs={'class':'form-control'}))

    contact_pref = forms.ChoiceField(choices=CONTACT_CHOICES,widget=forms.Select(attrs={'class':'custom-select'}))

    contact_suff =forms.IntegerField(widget=forms.NumberInput(attrs={'class':'form-control'}))

    job= forms.ChoiceField(choices=JOB_CHOICES,widget=forms.Select(attrs={'class':'custom-select'}))

    pwd1 = forms.CharField(max_length=20,widget=forms.PasswordInput(attrs={'class':'form-control'}))

    pwd2 = forms.CharField(max_length=20,widget=forms.PasswordInput(attrs={'class':'form-control'}))

    class Meta:
        model = UserInfoModel
        # fields = "__all__"
        exclude =("user",)

basic_app/views.py
from django.shortcuts import render
from basic_app import models

# from django.forms import ValidationError
from .forms import RegisterForm
from django.contrib.auth.models import User
# from django.http import HttpResponseRedirect

# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

def user_login(request):
    return render(request,'basic_app/login.html')


def user_register(request):

    template = 'basic_app/register.html'

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['fullname']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'Username already exists.'
                })
            elif User.objects.filter(email=form.cleaned_data['email']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'Email already exists.'
                })
            elif form.cleaned_data['pwd1'] != form.cleaned_data['pwd2']:
                return render(request, template, {
                    'form': form,
                    'error_message': 'Passwords do not match.'
                })
            else:
                # Create the user:
                user = User.objects.create_user(
                    form.cleaned_data['fullname'],
                    form.cleaned_data['email'],
                    form.cleaned_data['pwd1']
                )
                user.contact_pref = form.cleaned_data['contact_pref']
                user.contact_suff = form.cleaned_data['contact_suff']
                user.job = form.cleaned_data['job']
                user.save()
                return render(request, 'basic_app/index.html')   

        return render(request, template,{'form': form})
    else:
        form = RegisterForm()

    return render(request,template,{'form': form})

register/views.py
from django.shortcuts import render

# Create your views here.

# def user_register(request):

#     if request.method == 'POST':
#         data = dict(request.POST)
#         print('ALL DATA', data)
#         return render(request, 'basic_app/register.html')
#     return render(request,'basic_app/register.html')

templates/basic_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block title %} {% endblock %}
    <link rel="stylesheet" href="{% static 'css/all.css' %}" />
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <!-- Custom -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <!-- LightBox -->
    <link rel="stylesheet" href="{% static 'css/lightbox.min.css' %}" />
  </head>
  <body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">HOME</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'basic_app:index' %}">INDEX <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" href="{% url 'basic_app:login' %}">LOGIN</a>
                <a class="nav-item nav-link" href="{% url 'basic_app:register' %}">REGISTER</a>
                <!-- <a class="nav-item nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> -->
              </div>
            </div>
          </nav>
    </div>
    {% block content %} {% endblock %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %} "></script>
    <script src="{% static 'js/lightbox.min.js' %} "></script>
    <script src="{% static 'js/main.js' %} "></script>
  </body>
</html>

templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html "%}
{% block title %}

<title>INDEX</title>
{% endblock %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>INDEX PAGE</h1>
    </div>
</div>

{% endblock %}

templates/basic_app/login.html
<!DOCTYPE html>
{% extends "basic_app/base.html "%}
{% block title %}

<title>LOGIN</title>
{% endblock %}
{% block content %}
<h1>LOGIN</h1>
{% endblock %}

templates/basic_app/register.html
<!DOCTYPE html>
{% extends "basic_app/base.html "%} {% block title %}

<title>REGISTRATION</title>
{% endblock %} {% block content %}

<div class="container">
  <br />

  <div class="card bg-light">
   
      {% if error_message %}
      <div class="alert alert-danger">
      <p class="bg-danger p-d ml-b">{{ error_message }}</p>
    </div>
      {% endif %}
 
    <article class="card-body mx-auto" style="max-width: 400px;">
      <h4 class="card-title mt-3 text-center">Create Account</h4>
      <p class="text-center">Get started with your free account</p>
      <p>
        <a href="" class="btn btn-block btn-twitter">
          <i class="fab fa-twitter"></i> Login via Twitter</a
        >
        <a href="" class="btn btn-block btn-facebook">
          <i class="fab fa-facebook-f"></i> Login via facebook</a
        >
      </p>
      <p class="divider-text">
        <span class="bg-light">OR</span>
      </p>
      <form action="{% url 'basic_app:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-user"></i> </span>
          </div>
          <!-- <input
            name="fullname"
            class="form-control"
            placeholder="Full name"
            type="text"
          /> -->
          {{ form.fullname }}
        </div>
        <!-- form-group// -->
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">
              <i class="fa fa-envelope"></i>
            </span>
          </div>
          <!-- <input
            name="email"
            class="form-control"
            placeholder="Email address"
            type="email"
          /> -->
          {{ form.email }}
        </div>
        <!-- form-group// -->
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">
              <i class="fa fa-phone"></i>
            </span>
          </div>
          <!-- <select class="custom-select" style="max-width: 120px;" name="contact_pref">
            <option selected="">+971</option>
            <option value="1">+972</option>
            <option value="2">+198</option>
            <option value="3">+701</option>
          </select>
          <input
            name="contact_suff"
            class="form-control"
            placeholder="Phone number"
            type="text"
          /> -->
          {{ form.contact_pref }} {{ form.contact_suff }}
        </div>
        <!-- form-group// -->
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">
              <i class="fa fa-building"></i>
            </span>
          </div>
          <!-- <select class="form-control" name="job">
            <option selected=""> Select job type</option>
            <option>Designer</option>
            <option>Manager</option>
            <option>Accaunting</option>
          </select> -->
          {{ form.job }}
        </div>
        <!-- form-group end.// -->
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
          </div>
          <!-- <input
            class="form-control"
            placeholder="Create password"
            type="password"
            name ="pwd1"
          /> -->
          {{ form.pwd1 }}
        </div>
        <!-- form-group// -->
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
          </div>
          <!-- <input
            class="form-control"
            placeholder="Repeat password"
            type="password"
            name="pwd2"
          /> -->
          {{ form.pwd2 }}
        </div>
        <!-- form-group// -->
        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block">
            Create Account
          </button>
        </div>
        <!-- form-group// -->
        <p class="text-center">Have an account? <a href="">Log In</a></p>
      </form>
    </article>
  </div>
  <!-- card.// -->
</div>
<!--container end.//-->

{% endblock %}